sudo: required
services:
  - docker

before_install:
  - docker-compose build tests

script:
  - docker-compose up tests

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-ng"
  env: "DockerNg-env"
  bucket_name: "elasticbeanstalk-us-east-2-978828767084"
  bucket_path: "docker-ng"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
