version: '3'
services:
  web:
    build:
      context: .
      dockerfile:  Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    image: trion/ng-cli-karma:latest
    container_name: 'angular_karma'
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    ports:
      - 9876:9876
    command: >
      bash -c "ng test"
